dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DB=mysql57
  - DB=mysql56
install:
  # Needs a newer version of pip to do the pip installation line
  - pip install pip --upgrade
  - pip install .[test] nose
cache:
  apt: true
  pip: true
  directories:
  - $HOME/bins
before_script:
  - env | grep DB
  - bash -c "if [ '$DB' = 'mysql57' ]; then sudo ./scripts/install_mysql57.sh; fi"
  - bash -c "if [ '$DB' = 'mysql56' ]; then sudo ./scripts/install_mysql56.sh; fi"
  - which nosetests > ~/where-is-nosetests
script:
  - "sudo $(cat ~/where-is-nosetests) pymysqlreplication.tests.test_abnormal:TestAbnormalBinLogStreamReader.test_no_trailing_rotate_event"
  - "nosetests -e test_no_trailing_rotate_event"
