dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
env:
  - DB=mysql57
  - DB=mysql56
install:
  # Needs a newer version of pip to do the pip installation line
  - pip install pip --upgrade
  - pip install -e '.[test]'
  - pip install nose
cache:
  apt: true
  pip: true
  directories:
  - $HOME/bins
before_script:
  - env | grep DB
  - bash -c "if [ '$DB' = 'mysql57' ]; then sudo ./scripts/install_mysql57.sh; fi"
  - bash -c "if [ '$DB' = 'mysql56' ]; then sudo ./scripts/install_mysql56.sh; fi"
script:
  - "sudo $(which nosetests) pymysqlreplication.tests.test_abnormal:TestAbnormalBinLogStreamReader.test_no_trailing_rotate_event"
  - "nosetests -e test_no_trailing_rotate_event"

deploy:
  provider: pypi
  user: noplay
  password:
    secure: "uUIWiYzfgNTUuz4rKpNv/JFjnHncHPtBLiwhknCoaVJ9QGenpj9qaEWyvHZ/Aq4HyXCSjsogtQBesSxBTQCsrut6DDOWbOOFGr7WHA2N5O6EEu8rB7U4m+ziJn27+pN+MIl672tJGao7Ky9F+RO3X110Lscb0nguEMnWcHxb16U="
  on:
    tags: true
    repo: noplay/python-mysql-replication
